import { useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import ReactLoading from "react-loading";

import S from "../styles/Home.module.scss";
import Header from "../components/Header/index";
import BarOptions from "../components/BarOptions";
import { SessionContext } from "../provider/SessionContext";
import CardCryto from "../components/CardCrypto";

const Home: NextPage = () => {
  const { data, loading } = useContext(SessionContext);

  return (
    <div className={S.container}>
      <Head>
        <title>Klever</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kleverIcon.ico" />
      </Head>

      <Header />
      <BarOptions config={{ buttonEnable: true }} />
      <main className={S.main}>
        {loading ? (
          <ReactLoading
            className={S.spin}
            type="spin"
            color={"#fff"}
            height={"5%"}
            width={"5%"}
          />
        ) : (
          <section className={S.cardsContent}>
            <section className={S.headerDescription}>
              <p>Tokens</p>
              <p>Balance</p>
            </section>
            {data.map((token) => (
              <CardCryto key={token.id} token={token} />
            ))}
          </section>
        )}
      </main>
    </div>
  );
};

export default Home;
